package freebuff

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/entireio/external-agents/agents/entire-agent-freebuff/internal/protocol"
)

// Lifecycle hook names. Freebuff's engine does not yet expose a
// user-configurable hook registry, so the adapter declares the lifecycle
// surface it accepts via `entire hooks freebuff <name>` and records it in a
// repo-local registry (.freebuff/entire-hooks.json) that Freebuff
// wrappers/sessions can fire. Unknown hook names parse to null (ignored)
// instead of erroring, keeping older Checkpoint behaviour compatible.
const (
	HookNameSessionStart = "session-start"
	HookNamePromptSubmit = "prompt-submit"
	HookNameStop         = "stop"
	HookNameSessionEnd   = "session-end"

	hooksRegistryDir  = ".freebuff"
	hooksRegistryFile = "entire-hooks.json"
	registryMarker    = "// Auto-generated by `entire enable --agent freebuff` — Entire hook registry."
	activeSessionFile = "freebuff-active-session"
)

// hookRegistryDoc is the declarative registry written by install-hooks. It
// lists the lifecycle commands a Freebuff session wrapper must invoke so
// Entire can record the session.
type hookRegistryDoc struct {
	Marker      string              `json:"marker"`
	Commands    []hookRegistryEntry `json:"commands"`
	Agent       string              `json:"agent"`
	ProtocolVer int                 `json:"protocol_version"`
}

type hookRegistryEntry struct {
	Hook    string `json:"hook"`
	Command string `json:"command"`
	When    string `json:"when"`
}

func hookRegistryEntries() []hookRegistryEntry {
	return []hookRegistryEntry{
		{Hook: HookNameSessionStart, Command: "entire hooks freebuff " + HookNameSessionStart, When: "a Freebuff session starts (app launch / CLI start in this repo)"},
		{Hook: HookNamePromptSubmit, Command: "entire hooks freebuff " + HookNamePromptSubmit, When: "the user submits a prompt"},
		{Hook: HookNameStop, Command: "entire hooks freebuff " + HookNameStop, When: "the agent finishes a turn"},
		{Hook: HookNameSessionEnd, Command: "entire hooks freebuff " + HookNameSessionEnd, When: "the Freebuff session ends"},
	}
}

// parseHookPayload is the stdin payload a Freebuff wrapper sends to
// `entire hooks freebuff <name>`. It mirrors the protocol HookInput shape.
type parseHookPayload struct {
	HookType   string `json:"hook_type,omitempty"`
	SessionID  string `json:"session_id,omitempty"`
	SessionRef string `json:"session_ref,omitempty"`
	Timestamp  string `json:"timestamp,omitempty"`
	UserPrompt string `json:"user_prompt,omitempty"`
	Prompt     string `json:"prompt,omitempty"`
	Model      string `json:"model,omitempty"`
	CWD        string `json:"cwd,omitempty"`
}

func (a *Agent) ParseHook(hookName string, input []byte) (*protocol.EventJSON, error) {
	var payload parseHookPayload
	if len(bytes.TrimSpace(input)) > 0 {
		if err := json.Unmarshal(input, &payload); err != nil {
			// A malformed payload must not crash the lifecycle pipeline;
			// treat the event as absent.
			return nil, nil
		}
	}

	cwd := payload.CWD
	if cwd == "" {
		cwd = protocol.RepoRoot()
	}
	sessionID := payload.SessionID
	if sessionID == "" {
		sessionID = a.resolveSessionID(cwd, "")
	}

	now := payload.Timestamp
	if now == "" {
		now = time.Now().UTC().Format(time.RFC3339)
	}

	switch hookName {
	case HookNameSessionStart:
		writeRepoSessionCache(cwd, sessionID)
		return &protocol.EventJSON{
			Type:      1,
			SessionID: sessionID,
			Model:     payload.Model,
			Timestamp: now,
		}, nil
	case HookNamePromptSubmit:
		writeRepoSessionCache(cwd, sessionID)
		prompt := payload.Prompt
		if prompt == "" {
			prompt = payload.UserPrompt
		}
		return &protocol.EventJSON{
			Type:      2,
			SessionID: sessionID,
			Prompt:    prompt,
			Timestamp: now,
		}, nil
	case HookNameStop:
		sessionRef := payload.SessionRef
		if sessionRef == "" {
			if dir, err := a.GetSessionDir(cwd); err == nil {
				sessionRef = a.ResolveSessionFile(dir, sessionID)
			}
		}
		writeRepoSessionCache(cwd, sessionID)
		return &protocol.EventJSON{
			Type:       3,
			SessionID:  sessionID,
			SessionRef: sessionRef,
			Timestamp:  now,
		}, nil
	case HookNameSessionEnd:
		clearRepoSessionCache(cwd)
		return &protocol.EventJSON{
			Type:      5,
			SessionID: sessionID,
			Timestamp: now,
		}, nil
	default:
		// Unknown hook name — new lifecycle events must not break older
		// Checkpoint behaviour.
		return nil, nil
	}
}

func (a *Agent) InstallHooks(localDev bool, force bool) (int, error) {
	repoRoot := protocol.RepoRoot()
	if !force && a.AreHooksInstalled() {
		return 0, nil
	}
	doc := hookRegistryDoc{
		Marker:      registryMarker,
		Commands:    hookRegistryEntries(),
		Agent:       "freebuff",
		ProtocolVer: protocol.ProtocolVersion,
	}
	data, err := marshalJSON(doc)
	if err != nil {
		return 0, err
	}
	path := filepath.Join(repoRoot, hooksRegistryDir, hooksRegistryFile)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return 0, err
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return 0, err
	}
	return len(doc.Commands), nil
}

func (a *Agent) UninstallHooks() error {
	repoRoot := protocol.RepoRoot()
	path := filepath.Join(repoRoot, hooksRegistryDir, hooksRegistryFile)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	clearRepoSessionCache(repoRoot)
	return nil
}

func (a *Agent) AreHooksInstalled() bool {
	repoRoot := protocol.RepoRoot()
	path := filepath.Join(repoRoot, hooksRegistryDir, hooksRegistryFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	var doc hookRegistryDoc
	if json.Unmarshal(data, &doc) != nil {
		return false
	}
	return doc.Marker == registryMarker && len(doc.Commands) == len(hookRegistryEntries())
}

// repoSessionCachePath returns the repo-local active Freebuff session file
// under .entire/tmp, mirroring the other agents' sidecar convention.
func repoSessionCachePath(repoRoot string) string {
	return filepath.Join(repoRoot, ".entire", "tmp", activeSessionFile)
}

func readRepoSessionCache(repoRoot string) string {
	data, err := os.ReadFile(repoSessionCachePath(repoRoot))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}

func writeRepoSessionCache(repoRoot, sessionID string) {
	if sessionID == "" || sessionID == stubSessionID {
		return
	}
	path := repoSessionCachePath(repoRoot)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return
	}
	_ = os.WriteFile(path, []byte(sessionID), 0o600)
}

func clearRepoSessionCache(repoRoot string) {
	_ = os.Remove(repoSessionCachePath(repoRoot))
}

func generateSessionID() string {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("freebuff-%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(buf)
}

func marshalJSON(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
